### ISSUE TITLE
Deleted by mistake 

### ISSUE THREAD

**Issue by stevi09** [mattrubin/authenticator#349] opened 2021-02-02 14:08 UTC
Hello iv deleted a code on the app that I really need is ther a way to get it back

**Comment by cypsyx-bodzik-0bIfsa** [comment] 2021-02-03 04:46
#333 
@
![71B906A5-D987-4B1D-9F50-1859EFD8EBF9](https://user-images.githubusercontent.com/74800552/106699418-e77b2e00-65f3-11eb-9769-8b093ac3308c.jpeg)
Duplicate of #

> `[](https://github.com/mattrubin/Authenticator/issues/349#issue-799314625) `

**Comment by mattrubin** [comment] 2021-05-08 03:07
Your two-factor authentication tokens are only stored locally on your device, so if a token was deleted, it is difficult to recover. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you deleted the token, you could restore it to recover your two-factor tokens.
- Many websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some websites also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the website you no longer have access to and request their help recovering access to you accounts. If you're trying to access a Facebook account, [here](https://www.facebook.com/help/231208473756221) is their help article on how to recover an account that you can't log into.

I hope that helps!

**Closed as completed by mattrubin** 2021-05-08 03:07 UTC
Labels: lost tokens
